name: Update Contributors

on:
  schedule:
    - cron: '0 6 * * *'  # Diariamente às 6h UTC
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: pip install requests

      - name: Gerar contributors.md
        run: python scripts/generate_contributors.py

      - name: Commit e push se houver mudanças
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add content/contributors.md
          git diff --staged --quiet || git commit -m "🤖 Atualiza lista de contribuidores"
          git push